// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgQ1osu6Y98jh5-67CMaPvH1JakLOPzns',
    appId: '1:343396879737:web:ae6151d9ce48f174bc33a8',
    messagingSenderId: '343396879737',
    projectId: 'flutter-coffee-manager-web',
    authDomain: 'flutter-coffee-manager-web.firebaseapp.com',
    storageBucket: 'flutter-coffee-manager-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvAUb5lKLGOMUT8WisqmPXe71-SBkztU',
    appId: '1:343396879737:android:a4607b100eda7153bc33a8',
    messagingSenderId: '343396879737',
    projectId: 'flutter-coffee-manager-web',
    storageBucket: 'flutter-coffee-manager-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY6f9Z6y2EV61U3Icj95_IONr3zh-YDDo',
    appId: '1:343396879737:ios:8cf85fe6eaef73d0bc33a8',
    messagingSenderId: '343396879737',
    projectId: 'flutter-coffee-manager-web',
    storageBucket: 'flutter-coffee-manager-web.appspot.com',
    iosClientId: '343396879737-7nj4u5tll42c9a0cau5o5ne4k95mcc4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeManager',
  );
}
